name: C++ CI

permissions:
  contents: write

on:
  
  push:
    branches:
      - main
      - master
      - feature/github_actions
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-test-dev \
            doxygen

      - name: Configure project
        run: |
          cmake -S . -B build \
            -DPATCH_VERSION=${{ github.run_number }} \
            -DWITH_BOOST_TEST=ON

      - name: Build project
        run: |
          cmake --build build

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure

      - name: Build deb package
        run: |
          cmake --build build --target package

      - name: Debug deb files
        run: |
          echo "=== build directory ==="
          ls -lah build

      - name: Generate Doxygen documentation
        run: |
          doxygen Doxyfile

      - name: Deploy Doxygen to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/html
          force_orphan: true

      - name: Create Release and upload deb package
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: build/*.deb
          draft: false
          prerelease: false
